theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons2_add:
  - media
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - autoresize
  - media
width: '100%'
height: 400
autoresize_min_height: 400
autoresize_max_height: 800
mode: 'exact'
elements: 'file_description,news_content,discussion_content,entry_content,proposal_content,setting_home_main_content,page_blocks_attributes_1_content'